name: data
on:
  schedule:
    - cron: 55 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.weatherapi.com/v1/current.json?key=${{ secrets.API_KEY }}&q=Omsk&aqi=no
          downloaded_filename: weather.json
          postprocess: ./postprocess.ts
          mask: '["${{ secrets.API_KEY }}"]'
